name: Build project on Self-Hosted runner
on: 
  push: 

env:
  OPENSHIFT_NAMESPACE: github-runner
  # APP_NAME: "simple-quarkus-service-gh-action"
  # IMAGE_TAGS: latest-${{ github.sha }}
  # IMAGE_REGISTRY: quay.io/froberge

  AZURE_KEY_VAULT: githubaction-vault1
  AZURE_CREDENTIALS:  ${{ secrets.AZURE_CREDENTIALS }}

jobs: 
  azure_vault:
    name: Connec to Azure Key Vault
    runs-on: ubuntu-20.04
      
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Retrieve Key Vault Secrets
        id: secrets
        uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ env.AZURE_KEY_VAULT }}
          secrets: 'registry-user,registry-pwd,ocp-server,ocp-github-actions-sa-token, gh-access-pat'
    outputs:
      registry-user: ${{ steps.secrets.outputs.registry-user }}
      registry-pwd: ${{ steps.secrets.outputs.registry-pwd }}
      ocp-server: ${{ steps.secrets.outputs.ocp-server }}
      ocp-github-actions-sa-token: ${{ steps.secrets.outputs.ocp-github-actions-sa-token }}
      gh-access-pat: ${{ steps.secrets.outputs.gh-access-pat }}

  install_runner: 
    name: Install Runner 
    runs-on: ubuntu-20.04
    needs: azure_vault

    steps:
      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ needs.azure_vault.outputs.ocp-server }}
          openshift_token: ${{ needs.azure_vault.outputs.ocp-github-actions-sa-token }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
      
      - uses: redhat-actions/openshift-actions-runner-installer@v1 
        with: 
          github_pat: ${{ needs.azure_vault.outputs.gh-access-pat }}   
          # runner_location: redhat-actions                               
          # runner_image: quay.io/redhat-github-actions/java-runner-11 
          # runner_labels: openshift, java                                
  
  # build-quarkus: 
  #   name: Self Hosted Quarkus Build and Test
    
  #   runs-on: [ self-hosted, openshift, java ]             # Use the same labels we gave the runner above    
  #   needs: install_runner                                 # Wait until the job above completes

  #   env:
  #     WORKDIR: getting-started                  

  #   steps:
  #     - uses: actions/checkout@v2                         # Checkout a java project to build
  #       with:
  #         repository: redhat-actions/quarkus-quickstarts

  #     # https://github.com/redhat-actions/quarkus-quickstarts/tree/master/getting-started#readme

  #     - name: Install and build
  #       run: ./mvnw install -ntp
  #       working-directory: ${{ env.WORKDIR }}

  #     - name: Run tests
  #       run: ./mvnw test
  #       working-directory: ${{ env.WORKDIR }}

  #     - name: Upload jar artifacts
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: app-jar-files.zip
  #         path: ${{ env.WORKDIR }}/target/*.jar