name: Build Quarkus Application
on: 
  push:
    branches: [ main ]

env:
  OPENSHIFT_NAMESPACE: github-runner
  APP_NAME: "simple-quarkus-service-gh-action"
  TAGS: -${{ github.sha }}

  AZURE_KEY_VAULT: githubaction-vault1
  AZURE_CREDENTIALS:  ${{ secrets.AZURE_CREDENTIALS }}

jobs: 
  retrieve_secrets: 
    name: Retrieve Secrets
    runs-on: [  self-hosted, macOS, X64 ]

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Retrieve Key Vault Secrets
        id: az_secrets
        uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ env.AZURE_KEY_VAULT }}
          secrets: 'ocp-server,ocp-github-actions-sa-token, gh-access-pat'

      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ steps.az_secrets.outputs.ocp-server }}
          openshift_token: ${{ steps.az_secrets.outputs.ocp-github-actions-sa-token }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
      
      - uses: redhat-actions/openshift-actions-runner-installer@v1 
        with: 
          github_pat: ${{ steps.az_secrets.outputs.gh-access-pat }} 
          runner_labels: openshift, java
          # runner_location: redhat-actions                               
          runner_image: quay.io/redhat-github-actions/java-runner-11 
  
  build-quarkus: 
    name: Self Hosted Quarkus Build and Test
    runs-on: [ self-hosted, openshift, java ]          
    needs: retrieve_secrets                               

    env:
      WORKDIR: .                  

    steps:
      - uses: actions/checkout@v3
        with:
          repository: froberge/ocp-githubaction-azurevault-demo

      - name: Run tests
        run: ./mvnw test
        working-directory: ${{ env.WORKDIR }}

      - name: Clean and Package
        run: ./mvnw clean package
        working-directory: ${{ env.WORKDIR }}

      - name: Upload jar artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.APP_NAME}}-${{env.TAGS}}
          path: ${{ env.WORKDIR }}/target/quarkus-app/*
          